name: VPC CI/CD

on:
  push:
    branches:
      - main
  pull_request: {} # 空のままにする場合は中括弧を追加するか、以下のようにブランチを指定します

jobs:
  cfn-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install cfn-lint
        run: pip install cfn-lint

      - name: Run cfn-lint
        run: cfn-lint .github/workflows/cfn/vpc.yml # 拡張子を .yaml から .yml に修正
