name: AWS OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::473427586283:role/GitHubDeployRole
          aws-region: ap-northeast-1

      - name: Verify Identity
        run: aws sts get-caller-identity

      - name: Deploy VPC
        run: |
          aws cloudformation deploy \
            --stack-name vesta-vpc-dev \
            --template-file cfn/accounts/app/network/vpc.yaml \
            --region ap-northeast-1

      - name: Deploy Subnet
        run: |
          aws cloudformation deploy \
            --stack-name vesta-subnet-dev \
            --template-file cfn/accounts/app/network/subnet.yaml \
            --parameter-overrides VpcId=vpc-0446ede8899eef348 \
            --region ap-northeast-1

      - name: Deploy Route Association
        run: |
          aws cloudformation deploy \
            --stack-name vesta-route-dev \
            --template-file cfn/accounts/app/network/route.yaml \
            --parameter-overrides RouteTableId=rtb-05feff53d4df14233 SubnetId=subnet-0560ca82ddd230506 \
            --region ap-northeast-1